### PR TITLE
Convert to create/update to apply

### PR DESCRIPTION
**Pull request by mueschm**
## Description

To make things more clear to a user we no longer have create and update for dcs and envs. Instead you can now just run the apply command. This means a user no longer has to worry about if something was already created or new. On top of that this PR comes with a few other things.
1. When asking for an account for a datacenter variable, we no longer make them select a provider type first. The UX here was a bit confusing so this simplifies it.
2. We now have pipeline confirmations before any action is taken. We show the rendered pipeline and then ask the user if they are okay with the changes.
3. The render pipeline function now removes the header when it is done. This makes the UI look cleaner especially when you have multiple pipelines that are run back to back.
4. Added in a check to make sure docker is properly running and if not throw an informative error message. This was taken directly from the architect cli.

Closes [(issue 52)](https://github.com/architect-team/arcctl/issues/52)
Closes [(issue 66)](https://github.com/architect-team/arcctl/issues/66)
Closes [(issue 41)](https://github.com/architect-team/arcctl/issues/41)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Went through every flow. Though mainly testing the following
```
arcctl apply dc local __tests__/datacenters/local.yml --auto-approve
arcctl apply env -d local local __tests__/environment.yml --auto-approve
```
Though also tested `destroy`, `up` and `deploy` as well.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by davidthor** [comment]
This is fine, but it seems like a lot of code changes. Wouldn't it be easier to just put errors in the `testCredentials()` method and make sure we test the credentials before each service invocation?

**Comment by davidthor** [comment]
Also just tested locally and all appears in order, but this PR requires docs changes and despite you checking the box in the PR template you did NOT make docs changes :P 

Just update `./src/datacenters/README.md` with the new apply command and you're good to go.

**Comment by mueschm** [comment]
> This is fine, but it seems like a lot of code changes for the requires docker portion. Wouldn't it be easier to just put errors in the `testCredentials()` method and make sure we test the credentials before each service invocation?

**Comment by mueschm** [comment]
Alright updated everything. We now call `testCredentials` everywhere. 

For the documentation I just updated the commands, I kind of like how we split up talking about create and update so left that as is, but happy to change it if you disagree.

**Pull request merged**
