### PR TITLE
Randomized names for ingress rules when not assigned

### PR DESCRIPTION
**Pull request by davidthor**
## Description

We were previously running into a lot of collisions with subdomains within the environment since deploys would leave unassigned ingress rules with empty values for subdomain and path. This makes it very clunky to deploy since you need to explicitly assign subdomains to every ingress.

This PR uses a random name generator to assign randomized names to subdomains when there isn't one set explicitly. The generator also uses a tactic to ensure the same random subdomain is used for ingress rules on subsequent deploys which is really handy for remembering URLs:

Closes https://github.com/architect-team/arcctl/issues/136

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by mueschm** [comment]
I mean the code here is fine, but this feels odd to me. It would be odd to see a bunch of random domain names just popping up and them changing every run.

**Comment by davidthor** [comment]
> I mean the code here is fine, but this feels odd to me. It would be odd to see a bunch of random domain names just popping up and them changing every run.

They don’t change every run. The generator uses the node ID as a pinning value so that you’ll always get the same value for the same node ID.

But if that’s not enough do you have a better idea to solve the problem? My example component has 6 ingress rules across three components and assigning values for them all is annoying. Especially when I only care about the one web app that I’ll actually be opening manually (which can still be assigned with the “-i” flag).

**Comment by mueschm** [comment]
No that sounds good. Though did realize 1 potential issue and what happens if you don't want any subdomain because you want it to be the root domain?

**Comment by davidthor** [comment]
> No that sounds good. Though did realize 1 potential issue and what happens if you don't want any subdomain because you want it to be the root domain?

We talked about this offline and I think we're going to assume that use-case is done using the `@` symbol like many DNS providers. It'll be up to each arcctl provider to recognize this, but that should solve the problem.

**Review by TylerAldrich — APPROVED** [review]
This is good to go from my end - not sure if @mueschm had any more q's before we merge?

**Pull request merged**
